// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"shadow bg-gray-900 border-b border-b-blue-600\"><div class=\"container flex items-center justify-center p-6 mx-auto  capitalize text-gray-300\"><a href=\"#\" class=\"text-gray-200 transition-colors duration-300 transform text-gray-200 border-b-2 border-blue-500 mx-1.5 sm:mx-6\">home</a> <a href=\"/students\" class=\"text-gray-200 border-b-2 border-transparent hover:text-gray-300 transition-colors duration-300 transform  hover:border-blue-500 mx-1.5 sm:mx-6\">students</a> <a href=\"#\" class=\"text-gray-200 border-b-2 border-transparent hover:text-gray-300 transition-colors duration-300 transform  hover:border-blue-500 mx-1.5 sm:mx-6\">pricing</a> <a href=\"#\" class=\"text-gray-200 border-b-2 border-transparent hover:text-gray-300 transition-colors duration-300 transform hover:border-blue-500 mx-1.5 sm:mx-6\">blog</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
